herbalife/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('herbie.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

herbie/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .models import my_blog
from .views import BlogPostView,BlogDetailView
app_name = 'herbie'

urlpatterns = [
    path('',views.index,name='index'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('about/',views.about,name = 'about'),
    path('testimonials/',views.testimonials,name='testimonials'),
    path('register/',views.register,name = 'register'),
    path('dash/',views.dash,name = 'dash'),
    path('contact/',views.Contact,name='contact'),
    path('faq/',views.faq,name='faq'),
    path('services/',views.services,name='services'),
    path('blog/',BlogPostView.as_view(),name='blog'),
    path('single/<int:pk>/',BlogDetailView.as_view(),name='single'),
] 

herbie/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.exceptions import ValidationError


# Create your models here.
class testimonies(models.Model):
    title = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.TextField()
    img = models.ImageField(upload_to = 'pics')
    date = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.name
    
    
class contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = PhoneNumberField()
    message = models.TextField() 
    
    
    def __str__(self):
        return self.name
    

class my_blog(models.Model):
    title = models.CharField(max_length = 200)
    quote = models.CharField(max_length = 500,null=True,blank = True)
    intro = models.TextField(null=True,blank=True)
    content = models.TextField(null=True)
    image_one = models.ImageField(upload_to='pics')
    image_two = models.ImageField(upload_to='pics',null = True)    
    
    def __str__(self):
        return self.title   


def validate_only_one_instance(obj):
    model = obj.__class__
    if (model.objects.count() > 0 and obj.id != model.objects.get().id):
        raise ValidationError("Can only create one instance")
    

      
class SiteEditor(models.Model):
    home_Page_title_one = models.CharField(max_length=250)
    home_Page_title_two = models.CharField(max_length=250)
    home_page_title_background = models.ImageField(upload_to = 'pics',default = "pics/hero_1.jpg")
    home_page_title_background_two = models.ImageField(upload_to = 'pics',default="pics/hero_2.jpg")
    home_page_image_one = models.ImageField(upload_to = 'pics',default='pics\img_4.jpg')
    home_page_text_one = models.TextField()
    home_page_image_two = models.ImageField(upload_to = 'pics',default='pics\img_3.jpg')
    home_page_text_two = models.TextField()
    about_image = models.ImageField(upload_to = 'pics',default = 'pics\image_6.jpg')
    about_text = models.TextField(null = True)
    
    def clean(self):
        validate_only_one_instance(self)

    def __str__(self):
        return "site editor"

herbie/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import testimonies,my_blog,SiteEditor
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from .models import contact
from django.views.generic import ListView,DetailView

# Create your views here.
def index(request):
    return render(request,'herbie/index.html',context={'editor':SiteEditor.objects.all()})


def about(request):
    return render(request,'herbie/about.html',context={'editor':SiteEditor.objects.all()})

def testimonials(request):
    return render(request,'herbie/testimonials.html',context={'testimonies':testimonies.objects.all()})

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"Successfully registered:{username}")
            login(request,user)
            messages.info(request,f"you are logged in as:{username}")
            return redirect('herbie:about')
        
        
      #fix this part,always shows error for two password fields dont match,delete next two lines and use form design like crispy
      #cant have two users with same name
      
        else:
            return render(request,'herbie/register.html',context = {'form':form})  
    else:
        form = UserCreationForm()
        return render(request,'herbie/register.html',context = {'form':form})


def logout_view(request):
    logout(request)
    messages.info(request,f'Succesfully logged out')
    return redirect('herbie:index')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request,data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username,password =  password)
            if user is not None:
                login(request,user)
                messages.success(request,f'Successfully logged in as :{username}')
                return redirect('herbie:dash')
            else:
                return render(request,'herbie/login.html',context={'form':form})
        else:
            return render(request,'herbie/login.html',context={'form':form})
                   
    else:
        form = AuthenticationForm()
        return render(request,'herbie/login.html',context={'form':form})
    
    
@login_required
def dash(request):
    return render(request,'herbie/dash.html')


def Contact(request):
    if request.method == 'POST':
        nm = request.POST.get('name')
        eml = request.POST.get('email')
        phn = request.POST.get('phone')
        msg = request.POST.get('message')
        c = contact(name = nm,email = eml,phone = phn,message = msg)
        c.save()
        return render(request,'herbie/index.html')
    else:
        return render(request,'herbie/contact.html')
    
    
    
def faq(request):
    return render(request,'herbie/faq.html')
        
def services(request):
    return render(request,'herbie/services.html')

class BlogPostView(ListView):
    model = my_blog
    template_name = 'herbie/blog.html'
    context_object_name = 'blogs'

class BlogDetailView(DetailView):
    model = my_blog
    
    
        

herbie/templates/herbie/about.html
{% extends 'herbie/base.html' %}    
{% load static %}
{% block content %}

{% for edit in editor %}  
  <div class="site-half block">
    <div class="img-bg-1 right" style="background-image: url({{edit.about_image.url}});" data-aos="fade" data-aos-delay="100"></div>
    <div class="container">
      <div class="row no-gutters align-items-stretch">
        <div class="col-lg-5 mr-lg-auto py-5">
          <span class="caption d-block mb-2 font-secondary font-weight-bold">About us</span>
          <h2 class="site-section-heading text-uppercase font-secondary mb-5">Someone</h2>
                <p> {{edit.about_text}} </p>
        </div>
      </div>
    </div>
  </div>
    
{% endfor %}
            
      
            
          
  {% include 'herbie/includes/footer.html' %}


  {% endblock %}
  

herbie/templates/herbie/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>The Fit Life</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Work+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">    
    
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
  
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
  </head>
  <body>
    <div id="overlayer"></div>
    <div class="loader">
      <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  
    <div class="site-wrap">
  
      
  
      <div class="site-mobile-menu">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div> <!-- .site-mobile-menu -->

  {% include 'herbie/includes/navbar.html' %}
  {% include 'herbie/includes/messages.html' %}
  {% block content %}

  {% endblock %}  
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>

  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>

  
  </body>
</html>

herbie/templates/herbie/blog.html
{% extends 'herbie/base.html' %}
{% load static %}

{% block content %}
  
    <div class="site-blocks-cover inner-page overlay" style="background-image: url({% static 'images/hero_2.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-5 text-center" data-aos="fade">
          <h1 class="text-uppercase">Blog Posts</h1>
        </div>
      </div>
    </div>  

    <div class="slant-1"></div>

    
    
  <div class="site-section first-section" data-aos="fade">
      <div class="container">
        <div class="row mb-5">

      {% for b in blogs %}
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="media-image">
              <a href="{% url 'herbie:single' b.id %}"><img src="{{ b.image_one.url }}" alt="Image" class="img-fluid"></a>
              <div class="media-image-body">
                <h2 class="font-secondary text-uppercase"><a href="{% url 'herbie:single' b.id%}">{{ b.title }}</a></h2>
                <p>{{b.quote}}</p>
                <p><a href="{% url 'herbie:single' b.id %}">Read More</a></p>
              </div>
            </div>
          </div>
      {% endfor %}    
      

       
      </div>
    </div>

    

    


  {% include 'herbie/includes/footer.html' %}

{% endblock %}

herbie/templates/herbie/contact.html
{% extends 'herbie/base.html' %}
{% load static %}

{% block content %}

  <div class="site-blocks-cover inner-page overlay" style="background-image: url({% static 'images/hero_2.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-5 text-center" data-aos="fade">
        <h1 class="text-uppercase">Contact Us</h1>
      </div>
    </div>
  </div>  

  <div class="slant-1"></div>

  
  
<div class="site-section first-section" data-aos="fade">
    <div class="container">
      <div class="row">
     
        <div class="col-md-12 col-lg-8 mb-5">
        
          
        
          <form action="" method="post" class="p-5 bg-white">
              {% csrf_token %}
            <div class="row form-group">
              <div class="col-md-12 mb-3 mb-md-0">
                <label class="font-weight-bold" for="fullname">Full Name</label>
                <input type="text" name="name" id="fullname" class="form-control" placeholder="Full Name">
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                <label class="font-weight-bold" for="email">Email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Email Address">
              </div>
            </div>


            <div class="row form-group">
              <div class="col-md-12 mb-3 mb-md-0">
                <label class="font-weight-bold" for="phone">Phone</label>
                <input type="text" name="phone" id="phone" class="form-control" placeholder="Phone #">
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <label class="font-weight-bold" for="message">Message</label> 
                <textarea name="message" name="message" id="message" cols="30" rows="5" class="form-control" placeholder="Say hello to us"></textarea>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <input type="submit" value="Send Message" class="btn btn-primary text-white px-4 py-2">
              </div>
            </div>


          </form>
        </div>

        <div class="col-lg-4">
          <div class="p-4 mb-3 bg-white">
            <h3 class="h5 text-black mb-3">Contact Info</h3>
            <p class="mb-0 font-weight-bold">Address</p>
            <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

            <p class="mb-0 font-weight-bold">Phone</p>
            <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

            <p class="mb-0 font-weight-bold">Email Address</p>
            <p class="mb-0"><a href="#">youremail@domain.com</a></p>

          </div>
          
          
        </div>
      </div>
    </div>
  </div>
  {% include 'herbie/includes/footer.html' %}


{% endblock %}

herbie/templates/herbie/dash.html
{% extends 'herbie/base.html' %}

{% block content %}

dashboard



{% endblock %}

herbie/templates/herbie/faq.html
{% extends 'herbie/base.html' %}    
{% load static %}
  {% block content %}
 
  
    <div class="site-blocks-cover inner-page overlay" style="background-image: url({% static 'images/hero_2.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-5 text-center" data-aos="fade">
          <h1 class="text-uppercase">Frequently Ask Questions</h1>
        </div>
      </div>
    </div>  

    <div class="slant-1"></div>

    
    
    <div class="pb-3 site-section first-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12" data-aos="fade">
            <h2 class="site-section-heading text-center text-uppercase">Frequently Ask Questions</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="100">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> Where to find good hoes in pune?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>

          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="200">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> How much is the charge?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>

          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="100">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> Who is the author of this template?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>

          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="200">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> Is it free?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>

          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="100">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> Where to find your company?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>

          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="200">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> How much is the charge?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>

          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="100">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> Who is the author of this template?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>

          <div class="col-md-6 col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="200">
            <h3 class="d-flex align-items-center"><span class="circle-icon-wrap mr-3"><span class="icon-question"></span></span> Is it free?</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, sunt, laborum. Rem praesentium, necessitatibus obcaecati quas, aliquam quasi fugiat quod impedit dolorem itaque quis ab sed quibusdam, voluptatibus autem repudiandae.</p>
          </div>
        </div>
      </div>
    </div>

 
    {% include 'herbie/includes/footer.html' %}

{% endblock %}
 

herbie/templates/herbie/includes/footer.html
    <footer class="site-footer bg-dark">
        <div class="container">
          
  
          <div class="row">
            <div class="col-md-4 mb-4 mb-md-0">
              <h3 class="footer-heading mb-4 text-white">About</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat quos rem ullam, placeat amet.</p>
              <p><a href="{% url 'herbie:about' %}" class="btn btn-primary text-white px-4">Read More</a></p>
            </div>
            <div class="col-md-5 mb-4 mb-md-0 ml-auto">
              <div class="row mb-4">
                <div class="col-md-6">
                  <h3 class="footer-heading mb-4 text-white">Quick Menu</h3>
                    <ul class="list-unstyled">
                      <li><a href="{% url 'herbie:index' %}">Home</a></li>
                      <li><a href="{% url 'herbie:about' %}">About</a></li>
                      <li><a href="{% url 'herbie:blog' %}">Blog</a></li>
                      <li><a href="{% url 'herbie:contact' %}">Contacts</a></li>
                      
                    </ul>
                </div>
              </div>
  
              
  
            </div>
            <div class="col-md-2">
              
              <div class="row">
              <div class="col-md-12"><h3 class="footer-heading mb-4 text-white">Social Icons</h3></div>
                <div class="col-md-12">
                  <p>
                    <a href="#" class="pb-2 pr-2 pl-0"><span class="icon-facebook"></span></a>
                    <a href="#" class="p-2"><span class="icon-twitter"></span></a>
                    <a href="#" class="p-2"><span class="icon-instagram"></span></a>
                    <a href="#" class="p-2"><span class="icon-vimeo"></span></a>
  
                  </p>
                </div>
            </div>
            </div>
          </div>
          <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
              <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
  
              
            </div>
            
          </div>
        </div>
      </footer>
    </div>

herbie/templates/herbie/includes/messages.html
{% if messages %}
{% for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
      {{message}}
    </div>

    {% elif message.tags == 'info' %}
    <div class="alert alert-primary" role="alert">
      {{message}}
    </div>

    {% elif message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">
     {{message}}
    </div>

    {% elif message.tags == 'warning' %}
    <div class="alert alert-warning" role="alert">
      {{message}}
    </div>

    {% endif %}

{% endfor %}
{% endif %}

herbie/templates/herbie/includes/navbar.html
<div class="site-navbar-wrap js-site-navbar bg-white">
      
  <div class="container">
    <div class="site-navbar bg-light">
      <div class="row align-items-center">
        <div class="col-2">
          <h2 class="mb-0 site-logo"><a href="/" class="font-weight-bold text-uppercase">STAY-FIT</a></h2>
        </div>
        <div class="col-10">
          <nav class="site-navigation text-right" role="navigation">
            <div class="container">
              <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>

              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li class="active"><a href="/">Home</a></li>
                <li class="has-children">
                  <a href="{% url 'herbie:about' %}">About</a>
                  <ul class="dropdown arrow-top">
                    <li><a href="{% url 'herbie:testimonials' %}">Testimonials</a></li>
                    <li><a href="{% url 'herbie:faq' %}">FAQ</a></li>
                    <li><a href="{% url 'herbie:login' %}">Login</a></li>

                  </ul>
                </li>
                <li><a href="{% url 'herbie:services' %}">Services</a></li>
                <li><a href="{% url 'herbie:blog' %}">Blog</a></li>
                <li><a href="{% url 'herbie:contact' %}">Contact</a></li>
                <li><a href="{% url 'herbie:register' %}"><span class="d-inline-block bg-primary text-white btn btn-primary">Start Today</span></a></li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

herbie/templates/herbie/login.html
{% extends 'herbie/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

  <div class="site-blocks-cover inner-page overlay" style="background-image: url({% static 'images/hero_2.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-5 text-center" data-aos="fade">
        <h1 class="text-uppercase">Login</h1>
      </div>
    </div>
  </div>  

  <div class="slant-1"></div>

  
  
<div class="site-section first-section" data-aos="fade">
    <div class="container">
      <div class="row">
     
        <div class="col-md-12 col-lg-8 mb-5">
        
          
        
          <form action="" method="post" class="p-5 bg-white">
              {% csrf_token %}
            <div class="row form-group">
              <div class="col-md-12 mb-3 mb-md-0">
                {{ form|crispy }}
              </div>
            </div>
       

            <div class="row form-group">
              <div class="col-md-12">
                <input type="submit" value="Login" class="btn btn-primary text-white px-4 py-2">
              </div>
            </div>

            <div class = 'border-top-3'>
              <small class="text-muted">
                Dont have an account<a class = 'ml-2' href="{% url 'herbie:register' %}">register</a>
              </small>		
            </div>	


          </form>
        </div>

        <div class="col-lg-4">
          <div class="p-4 mb-3 bg-white">
            <h3 class="h5 text-black mb-3">Contact Info</h3>
            <p class="mb-0 font-weight-bold">Address</p>
            <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

            <p class="mb-0 font-weight-bold">Phone</p>
            <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

            <p class="mb-0 font-weight-bold">Email Address</p>
            <p class="mb-0"><a href="#">youremail@domain.com</a></p>

          </div>
          
          
        </div>
      </div>
    </div>
  </div>



  {% include 'herbie/includes/footer.html' %}


{% endblock %}

herbie/templates/herbie/register.html
{% extends 'herbie/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}



  <div class="site-blocks-cover inner-page overlay" style="background-image: url({% static 'images/hero_2.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-5 text-center" data-aos="fade">
        <h1 class="text-uppercase">Register</h1>
      </div>
    </div>
  </div>  

  <div class="slant-1"></div>

  
  
<div class="site-section first-section" data-aos="fade">
    <div class="container">
      <div class="row">
     
        <div class="col-md-12 col-lg-8 mb-5">
        
          
        
          <form action="" method="post" class="p-5 bg-white">
              {% csrf_token %}
            <div class="row form-group">
              <div class="col-md-12 mb-3 mb-md-0">
                {{ form|crispy }}
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <input type="submit" value="Login" class="btn btn-primary text-white px-4 py-2">
              </div>
            </div>
			<div class = 'border-top-3'>
				<small class="text-muted">
					Already have an account<a class = 'ml-2' href="{% url 'herbie:login' %}">Sign in</a>
				</small>		
			</div>	

          </form>
        </div>

        <div class="col-lg-4">
          <div class="p-4 mb-3 bg-white">
            <h3 class="h5 text-black mb-3">Contact Info</h3>
            <p class="mb-0 font-weight-bold">Address</p>
            <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

            <p class="mb-0 font-weight-bold">Phone</p>
            <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

            <p class="mb-0 font-weight-bold">Email Address</p>
            <p class="mb-0"><a href="#">youremail@domain.com</a></p>

          </div>
          
          
        </div>
      </div>
    </div>
  </div>

  {% include 'herbie/includes/footer.html' %}



{% endblock %}